sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker build -t dsa-online-proxy:$TRAVIS_BRANCH .
      - echo $REPO
      - docker push $REPO

