version: '3'

services:
    db: 
        image: mariadb:latest
        volumes:
            - db-data:/var/lib/mysql/
            - db-config-data:/etc/mysql/
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    frontend:
        image: failender/dsa-online-frontend:${DSA_ONLINE_VERSION}
        ports:
            - "${FRONTEND_PORT}:80"
    backend:
        image: failender/dsa-online-rest:${DSA_ONLINE_VERSION}
        ports:
            - "${BACKEND_PORT}:8080"
        environment:
            - spring.datasource.user:"root"
            - spring.datasource.password:${SQL_ROOT_PASSWORD}
            - spring.datasource.url:"jdbc:mysql://db:3306/dsa-online-rest"
            - dsa.online.cache.directory:"/cache"
volumes:
    db-data:
    db-config-data:
    