version: '3'

services:
  proxy:
    image: failender/dsa-online-proxy
    ports:
      - 80:80
      - 8080:8080
    restart: always
  db: 
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql/
      
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${dbpw}
    
  frontend:
    image: failender/dsa-online-frontend:${version}

  backend:
    image: failender/dsa-online-rest:${version}
    volumes:
      - rest-cache:/cache

    environment:
      - spring.datasource.username=root
      - spring.datasource.password=${dbpw}
      - spring.datasource.url=jdbc:mysql://db:3306/dsa
      - dsa.online.cache.directory=/cache
      - dsa.online.backend.version=${version}
      - dsa.online.frontend.version=${version}
volumes:
  db-data: {}
  rest-cache: {}
  
    